// Code generated by sqlc. DO NOT EDIT.
// source: transactions.sql

package db

import (
	"context"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
  id
) VALUES (
  $1
) RETURNING id, created_at
`

func (q *Queries) CreateTransaction(ctx context.Context, id string) (Transaction, error) {
	row := q.queryRow(ctx, q.createTransactionStmt, createTransaction, id)
	var i Transaction
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getMappingById = `-- name: GetMappingById :one
SELECT id, created_at FROM transactions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetMappingById(ctx context.Context, id string) (Transaction, error) {
	row := q.queryRow(ctx, q.getMappingByIdStmt, getMappingById, id)
	var i Transaction
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
