// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ConfigurationApi is an autogenerated mock type for the ConfigurationApi type
type ConfigurationApi struct {
	mock.Mock
}
