/*
 * Firefly III API
 *
 * This is the official documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. This version of the API is live from version v4.7.9 and onwards. You may use the \"Authorize\" button to try the API below. 
 *
 * API version: 1.4.0
 * Contact: james@firefly-iii.org
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package firefly

import (
	"encoding/json"
)

// AttachmentSingle struct for AttachmentSingle
type AttachmentSingle struct {
	Data AttachmentRead `json:"data"`
}

// NewAttachmentSingle instantiates a new AttachmentSingle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAttachmentSingle(data AttachmentRead) *AttachmentSingle {
	this := AttachmentSingle{}
	this.Data = data
	return &this
}

// NewAttachmentSingleWithDefaults instantiates a new AttachmentSingle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAttachmentSingleWithDefaults() *AttachmentSingle {
	this := AttachmentSingle{}
	return &this
}

// GetData returns the Data field value
func (o *AttachmentSingle) GetData() AttachmentRead {
	if o == nil {
		var ret AttachmentRead
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AttachmentSingle) GetDataOk() (*AttachmentRead, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *AttachmentSingle) SetData(v AttachmentRead) {
	o.Data = v
}

func (o AttachmentSingle) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableAttachmentSingle struct {
	value *AttachmentSingle
	isSet bool
}

func (v NullableAttachmentSingle) Get() *AttachmentSingle {
	return v.value
}

func (v *NullableAttachmentSingle) Set(val *AttachmentSingle) {
	v.value = val
	v.isSet = true
}

func (v NullableAttachmentSingle) IsSet() bool {
	return v.isSet
}

func (v *NullableAttachmentSingle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttachmentSingle(val *AttachmentSingle) *NullableAttachmentSingle {
	return &NullableAttachmentSingle{value: val, isSet: true}
}

func (v NullableAttachmentSingle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttachmentSingle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


