/*
 * Firefly III API v1.5.2
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2021-05-14T15:49:56+00:00 
 *
 * API version: 1.5.2
 * Contact: james@firefly-iii.org
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package firefly

import (
	"encoding/json"
)

// PiggyBankSingle struct for PiggyBankSingle
type PiggyBankSingle struct {
	Data PiggyBankRead `json:"data"`
}

// NewPiggyBankSingle instantiates a new PiggyBankSingle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPiggyBankSingle(data PiggyBankRead) *PiggyBankSingle {
	this := PiggyBankSingle{}
	this.Data = data
	return &this
}

// NewPiggyBankSingleWithDefaults instantiates a new PiggyBankSingle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPiggyBankSingleWithDefaults() *PiggyBankSingle {
	this := PiggyBankSingle{}
	return &this
}

// GetData returns the Data field value
func (o *PiggyBankSingle) GetData() PiggyBankRead {
	if o == nil {
		var ret PiggyBankRead
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PiggyBankSingle) GetDataOk() (*PiggyBankRead, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *PiggyBankSingle) SetData(v PiggyBankRead) {
	o.Data = v
}

func (o PiggyBankSingle) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullablePiggyBankSingle struct {
	value *PiggyBankSingle
	isSet bool
}

func (v NullablePiggyBankSingle) Get() *PiggyBankSingle {
	return v.value
}

func (v *NullablePiggyBankSingle) Set(val *PiggyBankSingle) {
	v.value = val
	v.isSet = true
}

func (v NullablePiggyBankSingle) IsSet() bool {
	return v.isSet
}

func (v *NullablePiggyBankSingle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePiggyBankSingle(val *PiggyBankSingle) *NullablePiggyBankSingle {
	return &NullablePiggyBankSingle{value: val, isSet: true}
}

func (v NullablePiggyBankSingle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePiggyBankSingle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


