/*
 * Firefly III API v1.5.2
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2021-05-14T15:49:56+00:00 
 *
 * API version: 1.5.2
 * Contact: james@firefly-iii.org
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package firefly

import (
	"encoding/json"
)

// RuleTriggerStore struct for RuleTriggerStore
type RuleTriggerStore struct {
	// The type of thing this trigger responds to. A limited set is possible
	Type string `json:"type"`
	// The accompanying value the trigger responds to. This value is often mandatory, but this depends on the trigger.
	Value string `json:"value"`
	// Order of the trigger
	Order *int32 `json:"order,omitempty"`
	// If the trigger is active. Defaults to true.
	Active *bool `json:"active,omitempty"`
	// When true, other triggers will not be checked if this trigger was triggered. Defaults to false.
	StopProcessing *bool `json:"stop_processing,omitempty"`
}

// NewRuleTriggerStore instantiates a new RuleTriggerStore object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRuleTriggerStore(type_ string, value string) *RuleTriggerStore {
	this := RuleTriggerStore{}
	this.Type = type_
	this.Value = value
	return &this
}

// NewRuleTriggerStoreWithDefaults instantiates a new RuleTriggerStore object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRuleTriggerStoreWithDefaults() *RuleTriggerStore {
	this := RuleTriggerStore{}
	return &this
}

// GetType returns the Type field value
func (o *RuleTriggerStore) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *RuleTriggerStore) GetTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *RuleTriggerStore) SetType(v string) {
	o.Type = v
}

// GetValue returns the Value field value
func (o *RuleTriggerStore) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *RuleTriggerStore) GetValueOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *RuleTriggerStore) SetValue(v string) {
	o.Value = v
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *RuleTriggerStore) GetOrder() int32 {
	if o == nil || o.Order == nil {
		var ret int32
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RuleTriggerStore) GetOrderOk() (*int32, bool) {
	if o == nil || o.Order == nil {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *RuleTriggerStore) HasOrder() bool {
	if o != nil && o.Order != nil {
		return true
	}

	return false
}

// SetOrder gets a reference to the given int32 and assigns it to the Order field.
func (o *RuleTriggerStore) SetOrder(v int32) {
	o.Order = &v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *RuleTriggerStore) GetActive() bool {
	if o == nil || o.Active == nil {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RuleTriggerStore) GetActiveOk() (*bool, bool) {
	if o == nil || o.Active == nil {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *RuleTriggerStore) HasActive() bool {
	if o != nil && o.Active != nil {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *RuleTriggerStore) SetActive(v bool) {
	o.Active = &v
}

// GetStopProcessing returns the StopProcessing field value if set, zero value otherwise.
func (o *RuleTriggerStore) GetStopProcessing() bool {
	if o == nil || o.StopProcessing == nil {
		var ret bool
		return ret
	}
	return *o.StopProcessing
}

// GetStopProcessingOk returns a tuple with the StopProcessing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RuleTriggerStore) GetStopProcessingOk() (*bool, bool) {
	if o == nil || o.StopProcessing == nil {
		return nil, false
	}
	return o.StopProcessing, true
}

// HasStopProcessing returns a boolean if a field has been set.
func (o *RuleTriggerStore) HasStopProcessing() bool {
	if o != nil && o.StopProcessing != nil {
		return true
	}

	return false
}

// SetStopProcessing gets a reference to the given bool and assigns it to the StopProcessing field.
func (o *RuleTriggerStore) SetStopProcessing(v bool) {
	o.StopProcessing = &v
}

func (o RuleTriggerStore) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["value"] = o.Value
	}
	if o.Order != nil {
		toSerialize["order"] = o.Order
	}
	if o.Active != nil {
		toSerialize["active"] = o.Active
	}
	if o.StopProcessing != nil {
		toSerialize["stop_processing"] = o.StopProcessing
	}
	return json.Marshal(toSerialize)
}

type NullableRuleTriggerStore struct {
	value *RuleTriggerStore
	isSet bool
}

func (v NullableRuleTriggerStore) Get() *RuleTriggerStore {
	return v.value
}

func (v *NullableRuleTriggerStore) Set(val *RuleTriggerStore) {
	v.value = val
	v.isSet = true
}

func (v NullableRuleTriggerStore) IsSet() bool {
	return v.isSet
}

func (v *NullableRuleTriggerStore) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRuleTriggerStore(val *RuleTriggerStore) *NullableRuleTriggerStore {
	return &NullableRuleTriggerStore{value: val, isSet: true}
}

func (v NullableRuleTriggerStore) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRuleTriggerStore) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


