/*
 * Firefly III API
 *
 * This is the official documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. This version of the API is live from version v4.7.9 and onwards. You may use the \"Authorize\" button to try the API below. 
 *
 * API version: 1.4.0
 * Contact: james@firefly-iii.org
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package firefly

import (
	"encoding/json"
)

// AutocompleteCurrency struct for AutocompleteCurrency
type AutocompleteCurrency struct {
	Id string `json:"id"`
	// Currency name.
	Name string `json:"name"`
	// Currency code for this account.
	Code string `json:"code"`
	Symbol string `json:"symbol"`
	DecimalPlaces int32 `json:"decimal_places"`
}

// NewAutocompleteCurrency instantiates a new AutocompleteCurrency object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAutocompleteCurrency(id string, name string, code string, symbol string, decimalPlaces int32) *AutocompleteCurrency {
	this := AutocompleteCurrency{}
	this.Id = id
	this.Name = name
	this.Code = code
	this.Symbol = symbol
	this.DecimalPlaces = decimalPlaces
	return &this
}

// NewAutocompleteCurrencyWithDefaults instantiates a new AutocompleteCurrency object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAutocompleteCurrencyWithDefaults() *AutocompleteCurrency {
	this := AutocompleteCurrency{}
	return &this
}

// GetId returns the Id field value
func (o *AutocompleteCurrency) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AutocompleteCurrency) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AutocompleteCurrency) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *AutocompleteCurrency) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AutocompleteCurrency) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AutocompleteCurrency) SetName(v string) {
	o.Name = v
}

// GetCode returns the Code field value
func (o *AutocompleteCurrency) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *AutocompleteCurrency) GetCodeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *AutocompleteCurrency) SetCode(v string) {
	o.Code = v
}

// GetSymbol returns the Symbol field value
func (o *AutocompleteCurrency) GetSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value
// and a boolean to check if the value has been set.
func (o *AutocompleteCurrency) GetSymbolOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Symbol, true
}

// SetSymbol sets field value
func (o *AutocompleteCurrency) SetSymbol(v string) {
	o.Symbol = v
}

// GetDecimalPlaces returns the DecimalPlaces field value
func (o *AutocompleteCurrency) GetDecimalPlaces() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DecimalPlaces
}

// GetDecimalPlacesOk returns a tuple with the DecimalPlaces field value
// and a boolean to check if the value has been set.
func (o *AutocompleteCurrency) GetDecimalPlacesOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DecimalPlaces, true
}

// SetDecimalPlaces sets field value
func (o *AutocompleteCurrency) SetDecimalPlaces(v int32) {
	o.DecimalPlaces = v
}

func (o AutocompleteCurrency) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["code"] = o.Code
	}
	if true {
		toSerialize["symbol"] = o.Symbol
	}
	if true {
		toSerialize["decimal_places"] = o.DecimalPlaces
	}
	return json.Marshal(toSerialize)
}

type NullableAutocompleteCurrency struct {
	value *AutocompleteCurrency
	isSet bool
}

func (v NullableAutocompleteCurrency) Get() *AutocompleteCurrency {
	return v.value
}

func (v *NullableAutocompleteCurrency) Set(val *AutocompleteCurrency) {
	v.value = val
	v.isSet = true
}

func (v NullableAutocompleteCurrency) IsSet() bool {
	return v.isSet
}

func (v *NullableAutocompleteCurrency) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAutocompleteCurrency(val *AutocompleteCurrency) *NullableAutocompleteCurrency {
	return &NullableAutocompleteCurrency{value: val, isSet: true}
}

func (v NullableAutocompleteCurrency) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAutocompleteCurrency) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


