/*
 * Firefly III API v1.5.2
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2021-05-14T15:49:56+00:00 
 *
 * API version: 1.5.2
 * Contact: james@firefly-iii.org
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package firefly

import (
	"encoding/json"
)

// WebhookSingle struct for WebhookSingle
type WebhookSingle struct {
	Data WebhookRead `json:"data"`
}

// NewWebhookSingle instantiates a new WebhookSingle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookSingle(data WebhookRead) *WebhookSingle {
	this := WebhookSingle{}
	this.Data = data
	return &this
}

// NewWebhookSingleWithDefaults instantiates a new WebhookSingle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookSingleWithDefaults() *WebhookSingle {
	this := WebhookSingle{}
	return &this
}

// GetData returns the Data field value
func (o *WebhookSingle) GetData() WebhookRead {
	if o == nil {
		var ret WebhookRead
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *WebhookSingle) GetDataOk() (*WebhookRead, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *WebhookSingle) SetData(v WebhookRead) {
	o.Data = v
}

func (o WebhookSingle) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableWebhookSingle struct {
	value *WebhookSingle
	isSet bool
}

func (v NullableWebhookSingle) Get() *WebhookSingle {
	return v.value
}

func (v *NullableWebhookSingle) Set(val *WebhookSingle) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookSingle) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookSingle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookSingle(val *WebhookSingle) *NullableWebhookSingle {
	return &NullableWebhookSingle{value: val, isSet: true}
}

func (v NullableWebhookSingle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookSingle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


