/*
 * Firefly III API v1.5.2
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2021-05-14T15:49:56+00:00 
 *
 * API version: 1.5.2
 * Contact: james@firefly-iii.org
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package firefly

import (
	"encoding/json"
)

// RuleSingle struct for RuleSingle
type RuleSingle struct {
	Data RuleRead `json:"data"`
}

// NewRuleSingle instantiates a new RuleSingle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRuleSingle(data RuleRead) *RuleSingle {
	this := RuleSingle{}
	this.Data = data
	return &this
}

// NewRuleSingleWithDefaults instantiates a new RuleSingle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRuleSingleWithDefaults() *RuleSingle {
	this := RuleSingle{}
	return &this
}

// GetData returns the Data field value
func (o *RuleSingle) GetData() RuleRead {
	if o == nil {
		var ret RuleRead
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *RuleSingle) GetDataOk() (*RuleRead, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *RuleSingle) SetData(v RuleRead) {
	o.Data = v
}

func (o RuleSingle) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableRuleSingle struct {
	value *RuleSingle
	isSet bool
}

func (v NullableRuleSingle) Get() *RuleSingle {
	return v.value
}

func (v *NullableRuleSingle) Set(val *RuleSingle) {
	v.value = val
	v.isSet = true
}

func (v NullableRuleSingle) IsSet() bool {
	return v.isSet
}

func (v *NullableRuleSingle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRuleSingle(val *RuleSingle) *NullableRuleSingle {
	return &NullableRuleSingle{value: val, isSet: true}
}

func (v NullableRuleSingle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRuleSingle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


