/*
 * Firefly III API v1.5.2
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2021-05-14T15:49:56+00:00 
 *
 * API version: 1.5.2
 * Contact: james@firefly-iii.org
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package firefly

import (
	"encoding/json"
)

// MetaPagination struct for MetaPagination
type MetaPagination struct {
	Total *int32 `json:"total,omitempty"`
	Count *int32 `json:"count,omitempty"`
	PerPage *int32 `json:"per_page,omitempty"`
	CurrentPage *int32 `json:"current_page,omitempty"`
	TotalPages *int32 `json:"total_pages,omitempty"`
}

// NewMetaPagination instantiates a new MetaPagination object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetaPagination() *MetaPagination {
	this := MetaPagination{}
	return &this
}

// NewMetaPaginationWithDefaults instantiates a new MetaPagination object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetaPaginationWithDefaults() *MetaPagination {
	this := MetaPagination{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *MetaPagination) GetTotal() int32 {
	if o == nil || o.Total == nil {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaPagination) GetTotalOk() (*int32, bool) {
	if o == nil || o.Total == nil {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *MetaPagination) HasTotal() bool {
	if o != nil && o.Total != nil {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *MetaPagination) SetTotal(v int32) {
	o.Total = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *MetaPagination) GetCount() int32 {
	if o == nil || o.Count == nil {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaPagination) GetCountOk() (*int32, bool) {
	if o == nil || o.Count == nil {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *MetaPagination) HasCount() bool {
	if o != nil && o.Count != nil {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *MetaPagination) SetCount(v int32) {
	o.Count = &v
}

// GetPerPage returns the PerPage field value if set, zero value otherwise.
func (o *MetaPagination) GetPerPage() int32 {
	if o == nil || o.PerPage == nil {
		var ret int32
		return ret
	}
	return *o.PerPage
}

// GetPerPageOk returns a tuple with the PerPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaPagination) GetPerPageOk() (*int32, bool) {
	if o == nil || o.PerPage == nil {
		return nil, false
	}
	return o.PerPage, true
}

// HasPerPage returns a boolean if a field has been set.
func (o *MetaPagination) HasPerPage() bool {
	if o != nil && o.PerPage != nil {
		return true
	}

	return false
}

// SetPerPage gets a reference to the given int32 and assigns it to the PerPage field.
func (o *MetaPagination) SetPerPage(v int32) {
	o.PerPage = &v
}

// GetCurrentPage returns the CurrentPage field value if set, zero value otherwise.
func (o *MetaPagination) GetCurrentPage() int32 {
	if o == nil || o.CurrentPage == nil {
		var ret int32
		return ret
	}
	return *o.CurrentPage
}

// GetCurrentPageOk returns a tuple with the CurrentPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaPagination) GetCurrentPageOk() (*int32, bool) {
	if o == nil || o.CurrentPage == nil {
		return nil, false
	}
	return o.CurrentPage, true
}

// HasCurrentPage returns a boolean if a field has been set.
func (o *MetaPagination) HasCurrentPage() bool {
	if o != nil && o.CurrentPage != nil {
		return true
	}

	return false
}

// SetCurrentPage gets a reference to the given int32 and assigns it to the CurrentPage field.
func (o *MetaPagination) SetCurrentPage(v int32) {
	o.CurrentPage = &v
}

// GetTotalPages returns the TotalPages field value if set, zero value otherwise.
func (o *MetaPagination) GetTotalPages() int32 {
	if o == nil || o.TotalPages == nil {
		var ret int32
		return ret
	}
	return *o.TotalPages
}

// GetTotalPagesOk returns a tuple with the TotalPages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaPagination) GetTotalPagesOk() (*int32, bool) {
	if o == nil || o.TotalPages == nil {
		return nil, false
	}
	return o.TotalPages, true
}

// HasTotalPages returns a boolean if a field has been set.
func (o *MetaPagination) HasTotalPages() bool {
	if o != nil && o.TotalPages != nil {
		return true
	}

	return false
}

// SetTotalPages gets a reference to the given int32 and assigns it to the TotalPages field.
func (o *MetaPagination) SetTotalPages(v int32) {
	o.TotalPages = &v
}

func (o MetaPagination) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Total != nil {
		toSerialize["total"] = o.Total
	}
	if o.Count != nil {
		toSerialize["count"] = o.Count
	}
	if o.PerPage != nil {
		toSerialize["per_page"] = o.PerPage
	}
	if o.CurrentPage != nil {
		toSerialize["current_page"] = o.CurrentPage
	}
	if o.TotalPages != nil {
		toSerialize["total_pages"] = o.TotalPages
	}
	return json.Marshal(toSerialize)
}

type NullableMetaPagination struct {
	value *MetaPagination
	isSet bool
}

func (v NullableMetaPagination) Get() *MetaPagination {
	return v.value
}

func (v *NullableMetaPagination) Set(val *MetaPagination) {
	v.value = val
	v.isSet = true
}

func (v NullableMetaPagination) IsSet() bool {
	return v.isSet
}

func (v *NullableMetaPagination) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetaPagination(val *MetaPagination) *NullableMetaPagination {
	return &NullableMetaPagination{value: val, isSet: true}
}

func (v NullableMetaPagination) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetaPagination) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


