name: GitHub Actions
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.16.6'
      - name: Go get
        run: go get ./...
      - name: Go vet
        run: go vet
      - name: Go test
        run: go test ./...
